README:
    - 'Here is a list of values you can use for the cursor fields.'
    - 'You can use the text value or the numeric value of the cursor.'
    - 'You can use lower or uppercase letters, and spaces instead of underscores.'
    - 'WHITE_POINTER (0)'
    - 'GREEN_POINTER (1)'
    - 'RED_POINTER (2)'
    - 'BLUE_POINTER (3)'
    - 'WHITE_CROSS (4)'
    - 'RED_MARKER (5)'
    - 'WHITE_CIRCLE (6)'
    - 'SMALL_WHITE_CIRCLE (7)'
    - 'MANSION (8)'
    - 'TEMPLE (9)'